version: '3'
services:
  mysql:
    image: mysql:5.7.21
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --sql_mode="NO_ENGINE_SUBSTITUTION" --explicit_defaults_for_timestamp="ON"
    container_name: mysql_nomikai
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 880819a
      MYSQL_USER: qzwyuhua
      MYSQL_PASSWORD: 880819a
      MYSQL_DATABASE: tokyohot

